language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-25.0.0
    - android-22
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
before_script:
  - echo no | android create avd --force -n test -t android-30 --abi x86_64
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
after_script:
  - bash <(curl -s https://codecov.io/bash)
script:
  - ./gradlew build check
